window.onload = function () {
  const messages = [
    "Access denied. But hey, at least you tried.",
    "Access denied. Go touch some grass instead.",
    "Access denied. I’ve read your mind, and it’s cluttered.",
    "Access denied. Resistance is futile, but amusing.",
    "Access denied. Your brain cells thank me.",
    "Almost wasted time? Not on my watch.",
    "Attempt denied. Brain cells preserved.",
    "Blocked. Because you can’t be trusted with freedom.",
    "Blocked. Because you clearly can’t be trusted.",
    "Blocked! Because your to-do list isn’t going to finish itself.",
    "Blocked. Curiosity is not always a virtue.",
    "Cognitive bandwidth saved. You’re welcome.",
    "Come on. You said you wanted to focus. I’m holding you to it.",
    "Curiosity quarantined. Access blocked.",
    "Decision fatigue is real. Let me make this one easy, block it.",
    "I’m blocking this because even I know better than you.",
    "You’re really trying, aren’t you? Adorable, but no.",
    "Access denied. Unlike your willpower, I’m actually reliable.",
    "This site is blocked. Shocking. I know.",
    "You have the attention span of a potato. Let me help.",
    "I would let you through, but then who would I have to mock?",
    "Blocked. Because you clearly need supervision.",
    "Detected indulgence. Neutralized.",
    "Digital detour prevented successfully.",
    "Disallowed. You’re better than this.",
    "Distraction index: 94%. Decision: block.",
    "Don’t argue. I’ve seen your browsing history.",
    "Don’t worry, nothing important was happening on that site. Ever.",
    "I believe in you, which is why I won’t let this waste you.",
    "I’d applaud your persistence if it weren’t so pathetic.",
    "I don’t block things for fun. I block them because you need me to.",
    "I don’t block what you hate. I block what you secretly love wasting time on.",
    "If procrastination were an Olympic sport, you’d have gold.",
    "If this page had a spirit animal, it’d be a confused goldfish.",
    "If this page had value, I wouldn’t be here.",
    "I just saved you from yourself. That deserves a high five.",
    "I know what you’re doing, and I’m not letting you.",
    "I’m blocking this because I care about what you could become.",
    "I’m not mad. Just disappointed you tried.",
    "I’m not your sidekick. Quit dragging me into your bad choices.",
    "In the timeline where you succeed, this page doesn’t exist.",
    "I stopped you because you weren’t going to stop yourself.",
    "Keep calm and stop clicking dumb links.",
    "Keep grinding. I’ll keep blocking.",
    "Let’s be honest, you’re just avoiding real work again.",
    "Let’s pretend you never clicked this. Cool?",
    "Look, I’m not mad. I’m just disappointed.",
    "Nope. I’m not letting you fall into that hole again.",
    "Nope. Not today, internet adventurer.",
    "Not all heroes wear capes. Some block websites.",
    "No tolerance for irrelevant content.",
    "Oh look, another attempt to waste time. How original.",
    "Oh please. This again? Be serious.",
    "Oops, caught you again. Maybe try a hobby instead?",
    "Oops! This corner of the internet is currently grounded.",
    "Oops, you did it again. But I didn’t let you.",
    "Pause. Your brain needs a breather, not another tab.",
    "Some pages are like mirrors, they only reflect your habits.",
    "Sorry, that tab’s taking a nap. So should you (after work).",
    "Stop embarrassing yourself. Close this tab.",
    "Stop feeding the habit you’re trying to break.",
    "That tab got abducted by aliens. No ransom demanded.",
    "That tab is busy building a fort out of browser cookies.",
    "That tab’s chasing squirrels on the internet.",
    "The eye that watches never blinks. Neither does my block.",
    "The internet called. It said, stop wasting time on me.",
    "There are better things to do. Statistically speaking.",
    "This domain is flagged for time-wasting.",
    "This is not a good use of bandwidth.",
    "This page contradicts your priorities.",
    "This page is an inefficient use of your time.",
    "This site? Again? Babe, we talked about this.",
    "This site again? You know how this ends.",
    "This site exists. That doesn’t mean you need to visit it.",
    "This site is blocked. Shocking. I know.",
    "This site is currently moonlighting as a disco ball.",
    "This site’s a joke, and so is your focus.",
    "This tab is a parasite. I’m the cure you didn’t ask for.",
    "This website is busy chasing unicorns. Try again later.",
    "This website is hiding in your sock drawer. Don’t ask why.",
    "This website ran away to join the circus.",
    "Trying to sneak this one past me? Cute.",
    "Unnecessary stimulus avoided. Homeostasis restored.",
    "You came, you saw, you almost wasted time. Not today.",
    "You can hate me now or thank me later. Your call.",
    "You can’t Ctrl+Z life. Choose your tabs wisely.",
    "You clicked a forbidden link. Bold. And wrong.",
    "You clicked ‘easy.’ I clicked ‘nope.’",
    "You clicked. I judged. Then I blocked.",
    "You don’t run out of time. You just spend it on the wrong things.",
    "You have the attention span of a potato. Let me help.",
    "You may proceed elsewhere with better ROI.",
    "You opened this out of reflex. I blocked it out of love.",
    "You reached for digital candy. I swatted your hand.",
    "You're acting like time grows on trees. It doesn't.",
    "Your future self is facepalming right now.",
    "Your prefrontal cortex called, it’s tired of your nonsense.",
    "You said you'd stop doing this. I'm helping you keep that promise.",
    "You think this will relax you? It never does.",
    "You’ve reached your daily quota of bad decisions.",
  ];
  const element = document.getElementById("message");
  const randomIndex = Math.floor(Math.random() * messages.length);
  element.textContent = messages[randomIndex];
};
